name : Medical_Experiments

on:
 push:
    branches : ["main"]
  pull_request:
        branches : ["main"]

permissions:
     contents : read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
           - users: actions/checkout@v3
           - name : Set Up Python 3.11
             users: actions/checkout@v3
             with:
                python-version : "3.11"

